dist: focal
osx_image: xcode13.1
language: node_js
compiler: gcc
env:
  global:
    - NATIVE_IMAGE_DIFF_SKIP_BINARY_DOWNLOAD_FOR_CI=true
    - NODE_LIBPNG_BINARY_URL=https://downloads.mailbutler.io/node/node-libpng
    # - secure: Gcpp1pwnwTJ/UmTF0VZtex9q8q4asJAoNImXNUbDkBaJMLn3rdHYdiiXErmVcx8924GuDeCcxTH0KS1owVmnaEMbOmhTLlh7ywNPviXkHRpr45TMsnhj0sKuCFNVy4G0GP+Edu6eOEBzCa5vOJ1B2ptj9whi1v1P032GXShzbWKOgtJR1J21EwvnhHjTxdCc39hCbtodqeHjTcczMClP8o50gjMdzAyNRjcMI2MARMIrgMPqbUzPHrcEoE3DBC+i+AWpcLY5iRyXo/RwcJxYjy2hUmSQMzlNmxExO8+cFVo8yQA3QU3qOTNL+c55OoARU+IwpeVsSFXRfhlKWFFCIlP02GoDU9K9CLNOR5Sx5NDkjldGz1KYUMDWTSMhVhH0XqyziM4fKHw+bmbZ2Z9qqZRgnLFunCiaM2L8RC7tzGo/voPsaHZB9SlBWVkPpvuF32IQl9cqYWgbiVOIHvPZ0EdlF9MHBKST8xc7FyFnMtsWkr05SPp7dg1ZCCI/2XbnP49Y4MiWeiQq8rno/OTUEaZCQVJuCqbx4/sBER1aHff6DP2Peu7wGPECcX6lickU9otvtGnMfM1U6Ig3q82mF8UHkcqWel0bB2BHEZMT1sfZI+kV/P7GLylFEfIuKBMAUXCZAWRWyLq1AcmkLM5na0nql43qLhs+EJAJCGxF2vU=
jobs:
  include:
    - stage: build
      node_js: "16"
      os: linux
    - stage: build
      node_js: "18"
      os: linux
    - stage: build
      node_js: "20"
      os: linux
    - stage: build
      node_js: "16"
      os: osx
      osx_image: xcode13.1
    - stage: build
      node_js: "18"
      os: osx
      osx_image: xcode13.1
    - stage: build
      node_js: "20"
      os: osx
      osx_image: xcode13.1
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - make
      - git
before_install:
  - npm install -g yarn
  - if [ $TRAVIS_OS_NAME == "linux" ]; then export CC="gcc-7"; export CXX="g++-7"; export
    LINK="gcc-7"; export LINKXX="g++-7"; fi
  - node --version
  - yarn --version
script:
  - make
# after_script:
#   - cat coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
cache: yarn
deploy:
  provider: releases
  api_key:
    secure: "j2zLZAQPjq3wbfUT2sKlM3vQ2iUc4uLNIiwcfsnT+PVLILizI0fdGPbjA+RfVYyHF+N2BPVFz7f+XUGt48wIYWR2jT0QhJI3cdVMv1KeawyQZahbVp8BEtNjr9rD3sn4b6F4UXmgJhVYwVDaa8nu5d/gzYQ8q2/w7YXi6T2Z5CvM71cM5plK9nFJViP2C+WY2RjadXwDxUaUEcxYnHNa233lH6NO/Wd+FZJo1G9JWTOy5z+hrmcmKS0VDe0WsMGGj2bookdz+u8UMC5iMUcjOA9d0mV7HVNFDnzwSZMIDbQmrKexOxl60NjsDA5xgUpCN0S1+YnADoZrJHeOtMUrCYsFvGl9k35sUC2NUSqynLXI7Ttv4XoOGqapaiWKksZD+1RPYLdjlX6wi9Nr/RyJEfDm9ho9Lx9eWBXU8W4ruYDA8RoZBW77Pnvq40VIQD9zm/q4Ths35tyF30gN4fMB6Z8mFdBKpQhnoOdxf6jyv46HWgQMGxQwoZ8OoUM7jKHtggLLGE4DTHVYgPRBYmp6XLAc3yQI0mQeOQNVB55pb1ZXLx+MrcURiixH/WKKc/O8vvzoOnMDzmcwiZeQps5pApMxZSl8yqtrdEc2MhQ3cOqWv5vmi3IIT6J/PixAoR//isc7da+iRuPeFULTtF8xKStaOLb0g/SZEn0pClhqVuU="
  file_glob: true
  file: native-image-diff-*-*-*.node
  skip_cleanup: true
  on:
    tags: true
